DATASETS:
  NAME: "TinyImageNet200"
  # SEED: 42 (unused)
  DATA_AUGMENTATION: "STANDARD"
  TINY:
    SHUFFLE_INDICES: False
    TRAIN_INDICES: [0, 90000,]
    VALID_INDICES: [90000, 100000,]

MODEL:
  META_ARCHITECTURE:
    NAME: "ImageClassificationModelBase"
  PIXEL_MEAN: [0.4802, 0.4481, 0.3976,]
  PIXEL_STD: [0.2770, 0.2691, 0.2822,]
  BACKBONE:
    NAME: "ResNet"
    RESNET:
      IN_PLANES: 64
      FIRST_BLOCK:
        USE_NORM_LAYER: True
        USE_ACTIVATION: True
        USE_POOL_LAYER: False
        CONV_KSP: [3, 1, 1,]
        # POOL_KSP: [3, 2, 1,] (unused)
      BLOCK: "BasicBlock"
      SHORTCUT: "ProjectionShortcut"
      NUM_BLOCKS: [2, 2, 2, 2,]
      WIDEN_FACTOR: 1
      CONV_LAYERS: "Conv2d"
      NORM_LAYERS: "BatchNorm2d"
      ACTIVATIONS: "ReLU"
  CLASSIFIER:
    NAME: "SoftmaxClassifier"
    SOFTMAX_CLASSIFIER:
      NUM_CLASSES: 200
      NUM_HEADS: 1
      USE_BIAS: True
      LINEAR_LAYERS: "Linear"
